.dockerignore, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/test.md, .github/ISSUE_TEMPLATE/todo.md, Dockerfile, src/main/resources/application-dev.yml
- dockerfile 추가
- layer 사용해서 최적화
- .dockerignore 추가
- Closes #24
=> [CI/CD] (Feature/024 cicd) dockerfile 구현

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/test.md, .github/ISSUE_TEMPLATE/todo.md, src/main/java/com/sprint/team2/monew/domain/notification/controller/NotificationController.java, src/main/java/com/sprint/team2/monew/domain/notification/dto/NotificationDto.java, src/main/java/com/sprint/team2/monew/domain/notification/entity/Notification.java, src/main/java/com/sprint/team2/monew/domain/notification/entity/ResourceType.java, src/main/java/com/sprint/team2/monew/domain/notification/mapper/NotificationMapper.java, src/main/java/com/sprint/team2/monew/domain/notification/service/NotificationService.java, src/main/java/com/sprint/team2/monew/domain/notification/service/basic/BasicNotificationsService.java
Notification Entity 설계
Enum 타입 (RESOURCE_TYPE ) 정의
NotificationDto 정의
- Closes #12
=>  [알림] (Feature/012) 도메인 모델 설계 및 구현

src/main/java/com/sprint/team2/monew/domain/user/controller/UserController.java, src/main/java/com/sprint/team2/monew/domain/user/entity/User.java, src/main/java/com/sprint/team2/monew/domain/user/repository/UserRepository.java, src/main/java/com/sprint/team2/monew/domain/user/service/UserService.java, src/main/java/com/sprint/team2/monew/domain/user/service/basic/BasicUserService.java
- **사용자 도메인 계층 구현**
- `user`
- `controller`
- `entity`
- `repository`
- `service`
- `basic`
(`dto`, `mapper`, `exception`은 다른 PR에서 함께 추가됩니다.)
- `dto`, `mapper`: #36 
- `exception`: #42 
<br>
- **엔티티 구현** (`user.entity`)
- `User`
- `email`
- `password`
- `nickname`
<br>
- **서비스 생성** (`user.service`)
- `UserService`  
- `BasicUserService`
<br>
- **컨트롤러 생성** (`user.controller`)
- `UserController`
<br>
- **리포지터리 생성** (`user.repository`)
- `UserRepository`  
- Closes #27 
- `@Column`에 `name` 속성 추가하였습니다.
=> [사용자](Feature/027) 사용자 베이스 생성(도메인 계층, 엔티티, 서비스, 컨트롤러, 리포지터리)

.github/workflows/deploy.yml, .github/workflows/test.yml, .gitignore, Dockerfile, README.md, src/main/java/com/sprint/team2/monew/domain/userActivity/controller/UserActivityController.java, src/main/java/com/sprint/team2/monew/domain/userActivity/dto/CommentActivityLikeDto.java, src/main/java/com/sprint/team2/monew/domain/userActivity/dto/response/UserActivityResponseDto.java, src/main/java/com/sprint/team2/monew/domain/userActivity/entity/UserActivity.java, src/main/java/com/sprint/team2/monew/domain/userActivity/mapper/UserActivityMapper.java, src/main/java/com/sprint/team2/monew/domain/userActivity/repository/UserActivityRepository.java, src/main/java/com/sprint/team2/monew/domain/userActivity/service/UserActivityService.java, src/main/java/com/sprint/team2/monew/domain/userActivity/service/basic/BasicUserService.java
[사용자 활동] (Feat:003) 사용자 활동 DTO 구현
- DTO 구현, 추가적으로 필요한 DTO 생성
- layered architecture 구조 틀 코드 추가
- Closes #3 
- Closes #89 
- x
- x
- UserActivityResponseDto, 그리고 CommentActivityLikeDto가 Swagger에 나온 형식과 맞는지만 가볍게 확인해주시면 될것 같습니다!
=> [사용자 활동] (Feat:003) DTO 구현

.github/workflows/deploy.yml, .github/workflows/test.yml, .gitignore, Dockerfile, README.md
[CI/CD] (Feat:011) CI/CD 파이프라인 완료
- deploy.yml 파일 완료
- jacoco 추가 (test.yml, README.md 파일에 추가)
- ECS, EDR 설정 완료 (+노션 추가)
- dummy .jar 파일 ecr에 추가 
- Github Secrets에 환경변수 추가
- Closes #11 
- x
- x
- deploy.yml에 흐름이 맞는지 확인해주시면 감사하겠습니다!
=> [CI/CD] (Feat:011) CI/CD 파이프라인 

src/main/java/com/sprint/team2/monew/global/config/MDCLoggingInterceptor.java, src/main/resources/logback-spring.xml
[Log] (fix/100) MDC 요청자IP 추가
- MDC에 요청자IP를 가져와 저장하도록 함
- 그에 따라 logback-spring.xml 코드 변경
- Closes #100 
- MDC에 요청자 IP주소 추가로 저장합니다.
- logback-spring.xml에서 관리하므로 따로 신경 쓰실건 없지만 메시지 내 IP 위치에 대한 피드백 있으면 수정하겠습니다.
=> [Log] (fix/100) MDC 요청자IP 추가

src/main/java/com/sprint/team2/monew/domain/userActivity/controller/UserActivityController.java, src/main/java/com/sprint/team2/monew/domain/userActivity/entity/UserActivity.java, src/main/java/com/sprint/team2/monew/domain/userActivity/mapper/UserActivityMapper.java, src/main/java/com/sprint/team2/monew/domain/userActivity/service/basic/BasicUserActivityService.java, src/main/resources/application-prod.yml
[활동 내역] (feature/145) 간단한 API 테스트
-MongoDB 로컬 테스트 완료
- Closes #145
- x
- x
- UserActivityController의 create 메서드, BasicUserActivityService의 create메서드만 간단하게 봐주시면 됩니다!
=> [활동 내역] (feature/145) 간단한 API 테스트

src/main/java/com/sprint/team2/monew/domain/article/service/basic/BasicArticleService.java, src/main/java/com/sprint/team2/monew/domain/like/service/basic/BasicReactionService.java, src/main/java/com/sprint/team2/monew/domain/notification/event/InterestArticleRegisteredEvent.java, src/main/java/com/sprint/team2/monew/domain/notification/service/basic/BasicNotificationsService.java, src/main/java/com/sprint/team2/monew/domain/subscription/repository/SubscriptionRepository.java, src/test/java/com/sprint/team2/monew/domain/notification/controller/NotificationControllerTest.java, src/test/java/com/sprint/team2/monew/domain/notification/service/NotificationServiceTest.java
- Article, Like
- BasicArticleService에 ApplicationEventPublisher 필드 추가 saveByInterest 메서드 내부에 이벤트 발행 코드 추가
-  BasicReactionService에 ApplicationEventPublisher필드 추가 likeComment메서드 내부 이벤트 발행 코드 추가
- Subscription
- SubscriptionRepository에 관심사 ID기반으로 유저 목록 조회하는 메서드 findUserIdsByInterestId()추가
- Notification
- InterestArticleRegisteredEvent 필드 수정 및 관련 서비스로직, 테스트 구조 변경  
- Closes #179 
- 중원님, 은수님께서 리뷰해주시면 좋을 것 같습니다!
=> [알림] (Feature/179) 알림 생성 기능 로직 수정 및 이벤트 발행 코드 추가

src/test/resources/application-test.yaml
- 기본 설정 파일에서 요구하는 환경 변수 값을 테스트 환경용으로 따로 오버라이딩하였습니다.
- Closes #232
=> [CI/CD] (Fix/232) 테스트 설정 파일 오버라이딩 추가

.github/workflows/cd.yml, Dockerfile, src/main/java/com/sprint/team2/monew/domain/userActivity/entity/UserActivity.java, src/main/java/com/sprint/team2/monew/domain/userActivity/listener/UserActivityListener.java, src/main/java/com/sprint/team2/monew/global/config/MongoConfig.java
[활동 내역] (Fix/271) 활동 내역 null 리턴값 고치기
- cd.yml 파일 수정
- 디버깅 로직 추가
- EnableMongoAuditing 추가
=> [활동 내역] (Fix/271) 활동 내역 null 리턴값 고치기

src/main/java/com/sprint/team2/monew/domain/article/controller/ArticleController.java, src/main/java/com/sprint/team2/monew/domain/article/service/ArticleService.java, src/main/java/com/sprint/team2/monew/domain/article/service/basic/BasicArticleService.java
- 출처 목록 기능 구현
- Closes #278 
- 
-
=> [뉴스 기사] (Feature/278) 출처 목록 기능 구현 

src/main/java/com/sprint/team2/monew/domain/notification/controller/NotificationController.java, src/main/java/com/sprint/team2/monew/domain/notification/repository/NotificationRepository.java, src/main/java/com/sprint/team2/monew/domain/notification/service/NotificationService.java, src/main/java/com/sprint/team2/monew/domain/notification/service/basic/BasicNotificationsService.java, src/test/java/com/sprint/team2/monew/domain/notification/controller/NotificationControllerTest.java, src/test/java/com/sprint/team2/monew/domain/notification/service/NotificationServiceTest.java
- 서비스 메서드 getAllNotifications에서 nextCursor를 인자로 받지 않아 커서 기반 페이지네이션이 실제로 동작하지 않고 있는 문제 해결
- Closes #250 
-
=> [알림] (Refactor/250) 알림 조회 커버 기반 페이지네이션 로직 수정

.github/workflows/ci.yml
- `test-schema.sql` 적용 이후 새로운 버그가 발견되어 `ci.yml`에 디버깅용 옵션을 적용하였습니다.
- Closes #255 
-
=> [CI/CD] (Fix/255) ci에 디버깅용 옵션 적용

src/main/java/com/sprint/team2/monew/domain/article/service/basic/BasicArticleService.java
- 메서드명 오타를 수정하였습니다. (`countByArticleId` -> `countByArticle_Id`)
- Closes #299 
-
=> [Article] (Fix/299) 메서드명 오타 수정

src/main/java/com/sprint/team2/monew/domain/article/batch/scheduler/NewsBatchScheduler.java
=> 알림 테스트위해 배치 시간 조정

src/test/java/com/sprint/team2/monew/domain/article/service/basic/BasicArticleServiceTest.java
[CI/CD] (Fix/323) Article 테스트코드 수정
- Article ApplicationEventPublisher 누락 수정
- Closes #323
- 로컬 테스트 문제 없음 확인했는데 오류가 발생할 수 도 있습니다!
=> [CI/CD] (Fix/323) Article 테스트코드 수정

src/main/java/com/sprint/team2/monew/domain/notification/mapper/NotificationMapper.java
- toNotifiactionDto에 필요한 매핑(@Mapping) 추가
- Closes #301 
-
=> [알림] (Fix/301) MapStruct 매핑 누락된 부분 추가

.github/workflows/ci.yml, src/main/java/com/sprint/team2/monew/global/log/FileWatchService.java, src/main/java/com/sprint/team2/monew/global/log/S3Uploader.java, src/main/resources/logback-spring.xml
[로그 관리] (Fix/328) 로그 관리 수정
- 로그 폴더 루트 수정
- Closes #328
- 
- ci에서 브랜치를 분기했더니 ci코드도 포함되어 있네요
- `ci.yml` 파일 제외하고 보시면 됩니다.
=> [로그 관리] (Fix/328) 로그 관리 수정

src/main/java/com/sprint/team2/monew/domain/article/batch/config/BackupBatchConfig.java
[뉴스 기사] 백업 배치 로그 추가
- Closes #
=> [뉴스 기사] 백업 배치 로그 추가

README.md
- readme 커버리지 뱃지 추가
- Closes #
- 
-
=> [Develop] (Doc) ReadMe 뱃지 추가

build.gradle
[뉴스 기사] (Fix/332) build.gradle 수정
- build.gradle에 jackson 관련 코드 추
- Closes # (332)
- 
-
=> [뉴스 기사] (Fix/332) 백업 - build.gradle 수정

build.gradle, src/main/java/com/sprint/team2/monew/domain/article/collect/RssCollector.java, src/main/java/com/sprint/team2/monew/domain/article/entity/ArticleSource.java, src/main/java/com/sprint/team2/monew/domain/article/service/basic/BasicArticleService.java, src/test/java/com/sprint/team2/monew/domain/article/collect/NaverApiCollectorTest.java
- RSS 뉴스 기사 수집 기능 구현
- 한국경제, 연합뉴스, 조선일보 추가
- Closes #167 
- 
- dependency추가해서 gradle 새로고침하셔야 합니다!
- test 코드는 일단 주석처리했습니다. 일단 버그들 좀 잡고 다시 테스트코드로 넘어올 예정입니다.
=> [뉴스 기사] (Feature/167) RSS 뉴스 기사 수집 기능 구현

build.gradle
[뉴스 기사 백업] build.gradle 수정
- 
- Closes #
- 
-
=> [뉴스 기사 백업] build.gradle 수정

src/test/java/com/sprint/team2/monew/domain/user/integration/UserCleanupJobE2ETest.java
[CI/CD] (Fix/352) CI 오류 해결
- CI 오류 해결
- CommentE2ETest에서 userRepo에 user생성 후 delete 안해서 발생하는 오류로 확인
- Closes #352
- 
-
=> [CI/CD] (Fix/352) CI 오류 해결

src/main/java/com/sprint/team2/monew/domain/like/service/basic/BasicReactionService.java, src/main/java/com/sprint/team2/monew/domain/userActivity/events/commentEvent/CommentLikeAddEvent.java, src/main/java/com/sprint/team2/monew/domain/userActivity/events/commentEvent/CommentLikeCancelEvent.java, src/main/java/com/sprint/team2/monew/domain/userActivity/listener/UserActivityListener.java, src/main/java/com/sprint/team2/monew/domain/userActivity/repository/UserActivityRepositoryCustom.java
[활동 내역] (Fix/354) 댓글 좋아요 반영 수정
- 댓글 좋아요 반영 수정
- 리포지토리 메서드 생성 
- 코드 수정
- Closes # (354)
- 댓글 서비스 부분에 조금 수정한게 있는데 그 부분은 은수님이 봐주시면 좋을것같습니다!
=> [활동 내역] (Fix/354) 댓글 좋아요 반영 수정

src/main/java/com/sprint/team2/monew/domain/userActivity/repository/UserActivityRepositoryCustom.java
[활동 내역] query 수정
- 
- Closes #
- 
-
=> [활동 내역] query 수정

src/test/java/com/sprint/team2/monew/domain/comment/e2e/CommentE2ETest.java
- 통합테스트에서 물리 삭제 시 알림과 좋아요가 삭제되는지 검증하는 구문을 추가하였습니다.
- Closes #192 
- 
-
=> [댓글] (feature/192) 통합테스트에서 물리 삭제 시 알림과 좋아요가 삭제되는지 검증하는 구문 추가

src/main/java/com/sprint/team2/monew/global/log/FileWatchService.java, src/main/resources/logback-spring.xml
[로그 관리] (Fix/374) 로그 적재 확인 후 시간별로 테스트한던거 날짜별로 변경
- 시간별로 테스트 하던거 날짜별로 변경
- Closes #374
- 
-
=> [로그 관리] (Fix/374) 로그 적재 확인 후 시간별로 테스트한던거 날짜별로 변경

src/main/java/com/sprint/team2/monew/domain/article/batch/config/BackupBatchConfig.java, src/main/java/com/sprint/team2/monew/domain/article/batch/scheduler/NewsBackupBatchScheduler.java, src/main/java/com/sprint/team2/monew/domain/article/entity/Article.java, src/main/java/com/sprint/team2/monew/domain/article/service/basic/BasicArticleStorageService.java
[뉴스 기사] (Fix/322) 뉴스 기사 복구 오류 
- s3에 업로드라고 읽어오는 오류 해결
- Closes # (322)
=> [뉴스 기사] (Fix/322) 뉴스 기사 복구 오류 

src/main/java/com/sprint/team2/monew/domain/article/batch/config/BackupBatchConfig.java, src/main/java/com/sprint/team2/monew/domain/article/batch/scheduler/NewsBackupBatchScheduler.java, src/main/java/com/sprint/team2/monew/domain/article/batch/scheduler/TestJobRunner.java, src/main/java/com/sprint/team2/monew/domain/article/repository/ArticleRepository.java, src/main/java/com/sprint/team2/monew/domain/article/service/basic/BasicArticleStorageService.java
[뉴스 기사] (feature/322) test용 복구 기능 추가
- test용 복구 기능 추가
- 로컬에서는 잘 복구가 됩니다!
- cron job 시간 수정
- Closes #322
- 
-
=> [뉴스 기사] (feature/322) test용 복구 기능 추가, cron job 시간 변경

src/main/java/com/sprint/team2/monew/domain/notification/repository/NotificationRepository.java, src/test/java/com/sprint/team2/monew/domain/notification/integration/NotificationIntegrationTest.java
- 통합테스트 추가
- 레포지토리 메서드 추가
- Closes #288 
-
=> [알림] (Feature/288) 알림 통합테스트 추가

src/main/java/com/sprint/team2/monew/domain/article/entity/ArticleSource.java
- 한글 표시로 보이게 추가
- Closes #
- 
- 전에 구현해놨는데 PR 내역에서 빠져있어서 다시 PR 올립니다...
=> [뉴스 기사] (feature/167) 출처 목록에 한글 표시로 보이게 추가

src/test/java/com/sprint/team2/monew/domain/notification/integration/NotificationIntegrationTest.java
- CI 테스트 오류 해결을 위한 알림 통합테스트 코드 수정
- Closes #389 
-
=> [알림] (Fix/389) CI 테스트 오류 해결

src/main/java/com/sprint/team2/monew/MonewApplication.java
[뉴스 기사] postConstruct 추가
- 
- Closes #
- 
-
=> [뉴스 기사] postConstruct 추가

src/main/java/com/sprint/team2/monew/domain/article/batch/config/BackupBatchConfig.java, src/main/java/com/sprint/team2/monew/domain/article/service/basic/BasicArticleStorageService.java
[뉴스 기사] (fix/398) 뉴스 기사 복구 오류
- 기사 중복 제거
- Closes # (398)
- 
-
=> [뉴스 기사] (fix/398) 뉴스 기사 복구 오류

src/main/java/com/sprint/team2/monew/domain/article/batch/scheduler/TestJobRunner.java
[뉴스 기사] 뉴스 기사 복구 - testjobrunner 주석처리
- 
- Closes #
- 
-
=> [뉴스 기사] 뉴스 기사 복구 - testjobrunner 주석처리

README.md
[Document] (document/409) README 기술 스택 변경
- README 기술 스택 변경
- Closes #409
=> [Document] (document/409) README 기술 스택 변경

.github/workflows/cd.yml, .github/workflows/ci.yml
[CI/CD] (Feature/421) on push branch를 main으로 변경
- on push branch를 main으로 변경
- Closes #421
=> [CI/CD] (Feature/421) on push branch를 main으로 변경
